# Generated by Django 2.2.1 on 2019-07-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apk_uploadfile',
            name='md5',
            field=models.CharField(default=None, max_length=64, verbose_name='MD5'),
        ),
    ]
