# Generated by Django 2.2.1 on 2019-08-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0002_apk_uploadfile_md5'),
    ]

    operations = [
        migrations.AddField(
            model_name='apk_uploadfile',
            name='packagename',
            field=models.CharField(default=1, max_length=50, verbose_name='packagename'),
            preserve_default=False,
        ),
    ]
